// This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

using Kaitai;

namespace Gale.EOS.Kaitai.EU
{

    /// <summary>
    /// Holds bitsized data for the parent enum music_id.
    /// </summary>
    public partial class MusicId16 : KaitaiStruct
    {
        public static MusicId16 FromFile(string fileName)
        {
            return new MusicId16(new KaitaiStream(fileName));
        }


        public enum MusicId16Enum
        {
            MusicNone0x0 = 0,
            MusicPokemonExplorationTeamTheme = 1,
            MusicTopMenuTheme = 2,
            MusicMarowakDojo = 3,
            MusicTheGatekeepers = 4,
            MusicJobClear = 5,
            MusicWelcomeToTheWorldOfPokemon = 6,
            MusicWigglytuffsGuild = 7,
            MusicWigglytuffsGuildRemix = 8,
            MusicTreasureTown = 9,
            MusicDoYourBestAsAlways = 10,
            MusicMonsterHouse = 11,
            MusicKecleonsShop = 12,
            MusicOutlaw = 13,
            MusicInTheDepthsOfThePit = 14,
            MusicBossBattle = 15,
            MusicDialgasFightToTheFinish = 16,
            MusicBattleAgainstDusknoir = 17,
            MusicDefyTheLegends = 18,
            MusicMissionFailure = 19,
            MusicMissionSuccess = 20,
            MusicBeachCave = 21,
            MusicDrenchedBluff = 22,
            MusicMtBristle = 23,
            MusicWaterfallCave = 24,
            MusicAppleWoods = 25,
            MusicCraggyCoast = 26,
            MusicCaveAndSidePath = 27,
            MusicMtHorn = 28,
            MusicFoggyForest = 29,
            MusicSteamCave = 30,
            MusicUpperSteamCave = 31,
            MusicAmpPlains = 32,
            MusicFarAmpPlains = 33,
            MusicNorthernDesert = 34,
            MusicQuicksandCave = 35,
            MusicQuicksandPit = 36,
            MusicCrystalCave = 37,
            MusicCrystalCrossing = 38,
            MusicChasmCave = 39,
            MusicDarkHill = 40,
            MusicSealedRuin = 41,
            MusicDeepSealedRuin = 42,
            MusicDuskForest = 43,
            MusicDeepDuskForest = 44,
            MusicRandomDungeonTheme2 = 45,
            MusicBrineCave = 46,
            MusicLowerBrineCave = 47,
            MusicHiddenLand = 48,
            MusicHiddenHighland = 49,
            MusicTemporalTower = 50,
            MusicTemporalSpire = 51,
            MusicMystifyingForest = 52,
            MusicBlizzardIslandRescueTeamMedley = 53,
            MusicSurroundedSea = 54,
            MusicRandomDungeonTheme1 = 55,
            MusicAegisCave = 56,
            MusicConcealedRuins = 57,
            MusicMtTravail = 58,
            MusicInTheNightmare = 59,
            MusicMiracleSea = 60,
            MusicTreeshroudForest = 61,
            MusicDarkCrater = 62,
            MusicDeepDarkCrater = 63,
            MusicIntroAlternateUnused = 64,
            MusicPerfectSentryDuty = 65,
            MusicGoodSentryDuty = 66,
            MusicDecentSentryDuty = 67,
            MusicFailedSentryDuty = 68,
            MusicOnTheBeachAtDusk = 69,
            MusicGoodnight = 70,
            MusicGoodnightAlternateUnused = 71,
            MusicAtTheEndOfTheDay = 72,
            MusicGuildmasterWigglytuff = 73,
            MusicGrowingAnxiety = 74,
            MusicThePowerOfDarkness = 75,
            MusicOhNo = 76,
            MusicTimeGear = 77,
            MusicTimeGearRemix = 78,
            MusicISawSomethingAgain = 79,
            MusicInTheFuture = 80,
            MusicPlanetsParalysis = 81,
            MusicThroughTheSeaOfTime = 82,
            MusicInTheHandsOfFate = 83,
            MusicTimeRestored = 84,
            MusicDontEverForget = 85,
            MusicAWishForPeace = 86,
            MusicOnTheBeachAtDuskIntroOnly = 87,
            MusicMemoriesReturned = 88,
            MusicEndingThemeIntro = 89,
            MusicEndingTheme = 90,
            MusicEpilogueTheme = 91,
            MusicTitleThemeAlternate1Unused = 92,
            MusicTitleThemeAlternate2Unused = 93,
            MusicMurkyForest = 94,
            MusicSkyPeakCave = 95,
            MusicSouthernJungle = 96,
            MusicSkyPeakCoast = 97,
            MusicSpringCave = 98,
            MusicLowerSpringCave = 99,
            MusicOceanSfx = 100,
            MusicThunderstormSfx = 101,
            MusicThunderstormMuffledSfx = 102,
            MusicRumblingSfx = 103,
            MusicRumblingLouderSfx = 104,
            MusicRumblingLoudestSfx = 105,
            MusicRunningHotWaterSfx = 106,
            MusicTemporalPinnacleSfx = 107,
            MusicTemporalPinnacle = 108,
            MusicNull0x6d = 109,
            MusicHeavyFootstepsSfx = 110,
            MusicSingleToneRingingSfx = 111,
            MusicElectricitySfx1 = 112,
            MusicElectricitySfx2 = 113,
            MusicElectricitySfx3 = 114,
            MusicFireCracklingSfx1 = 115,
            MusicFireCracklingSfx2 = 116,
            MusicRelicFragmentSfx = 117,
            MusicRainbowStoneshipSfx = 118,
            MusicRainbowStoneshipPreparingSfx = 119,
            MusicHummingSfx = 120,
            MusicHaveToGetHome = 121,
            MusicFartherAway = 122,
            MusicPalkiasOnslaught = 123,
            MusicNone0x7c = 124,
            MusicWaterfallSfx = 125,
            MusicEatingSfx = 126,
            MusicOminousStringNoteSfx = 127,
            MusicFloodSfx = 128,
            MusicPelipperIsland = 129,
            MusicTitleTheme = 130,
            MusicHeartwarming = 131,
            MusicDownADarkPath = 132,
            MusicRisingFear = 133,
            MusicTeamSkull = 134,
            MusicSympathy = 135,
            MusicBeyondTheDream = 136,
            MusicAirOfUnease = 137,
            MusicOneForAll = 138,
            MusicAllForOne = 139,
            MusicBoulderQuarry = 140,
            MusicSpringCaveDepths = 141,
            MusicStarCave = 142,
            MusicDeepStarCave = 143,
            MusicLimestoneCave = 144,
            MusicDeepLimestoneCave = 145,
            MusicRandomDungeonTheme3 = 146,
            MusicFortuneRavine = 147,
            MusicFortuneRavineDepths = 148,
            MusicBarrenValley = 149,
            MusicDarkWasteland = 150,
            MusicSpacialCliffs = 151,
            MusicDarkIceMountain = 152,
            MusicIcicleForest = 153,
            MusicVastIceMountain = 154,
            MusicVastIceMountainPeak = 155,
            MusicSkyPeakForest = 156,
            MusicSkyPeakPrairie = 157,
            MusicSkyPeakSnowfield = 158,
            MusicSkyPeakFinalPass = 159,
            MusicSpindasCafe = 160,
            MusicLudicoloDance = 161,
            MusicIllusionStoneChamber = 162,
            MusicItCantBe = 163,
            MusicDefendGlobe = 164,
            MusicDefendGlobeEnding = 165,
            MusicTeamCharmsTheme = 166,
            MusicHereComesTeamCharm = 167,
            MusicForANewLife = 168,
            MusicLivingSpirit = 169,
            MusicProudAccomplishment = 170,
            MusicInTheMorningSun = 171,
            MusicANewWorld = 172,
            MusicThoughtsForFriends = 173,
            MusicLifeGoesOnEnding = 174,
            MusicItsNotAMiracle = 175,
            MusicAMessageOnTheWind = 176,
            MusicAFunExploration = 177,
            MusicShayminVillage = 178,
            MusicTeamCharmsThemeIntroOnly = 179,
            MusicRumblingSfx4 = 180,
            MusicRumblingSfx5 = 181,
            MusicOceanMuffledSfx = 182,
            MusicWindSfx1 = 183,
            MusicLimestoneCavernDepthsSfx = 184,
            MusicFireCracklingSfx3 = 185,
            MusicSkyPeak8thStationClearingSfx = 186,
            MusicWindAndRainSfx = 187,
            MusicVastIceMountainPinnacleSfx = 188,
            MusicSpringCaveSfx = 189,
            MusicWindSfx2 = 190,
            MusicSouthernJungleExitSfx = 191,
            MusicBoulderQuarryClearingSfx = 192,
            MusicWaterfallCaveVisionSfx = 193,
            MusicWindSfx3 = 194,
            MusicNull0xc2 = 195,
            MusicNull0xc3 = 196,
            MusicNull0xc4 = 197,
            MusicNull0xc5 = 198,
            MusicNull0xc6 = 199,
            MusicTeamCharmsThemeAlternate1Unused = 200,
            MusicTeamCharmJingle = 201,
            MusicTeamCharmsThemeAlternate2Unused = 202,
            MusicNone0x3e7 = 999,
        }
        public MusicId16(KaitaiStream p__io, KaitaiStruct p__parent = null, MusicId16 p__root = null) : base(p__io)
        {
            m_parent = p__parent;
            m_root = p__root ?? this;
            _read();
        }
        private void _read()
        {
            _musicId16Value = ((MusicId16Enum) m_io.ReadBitsIntLe(16));
        }
        private MusicId16Enum _musicId16Value;
        private MusicId16 m_root;
        private KaitaiStruct m_parent;
        public MusicId16Enum MusicId16Value { get { return _musicId16Value; } }
        public MusicId16 M_Root { get { return m_root; } }
        public KaitaiStruct M_Parent { get { return m_parent; } }
    }
}
