// This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

using Kaitai;

namespace Gale.EOS.Kaitai.NA
{

    /// <summary>
    /// Holds bitsized data for the parent enum dungeon_id.
    /// </summary>
    public partial class DungeonId8 : KaitaiStruct
    {
        public static DungeonId8 FromFile(string fileName)
        {
            return new DungeonId8(new KaitaiStream(fileName));
        }


        public enum DungeonId8Enum
        {
            DungeonTestDungeon = 0,
            DungeonBeachCave = 1,
            DungeonBeachCavePit = 2,
            DungeonDrenchedBluff = 3,
            DungeonMtBristle = 4,
            DungeonMtBristlePeak = 5,
            DungeonWaterfallCave = 6,
            DungeonAppleWoods = 7,
            DungeonCraggyCoast = 8,
            DungeonSidePath = 9,
            DungeonMtHorn = 10,
            DungeonRockPath = 11,
            DungeonFoggyForest = 12,
            DungeonForestPath = 13,
            DungeonSteamCave = 14,
            DungeonUpperSteamCave = 15,
            DungeonSteamCavePeak = 16,
            DungeonAmpPlains = 17,
            DungeonFarAmpPlains = 18,
            DungeonAmpClearing = 19,
            DungeonNorthernDesert = 20,
            DungeonQuicksandCave = 21,
            DungeonQuicksandPit = 22,
            DungeonUndergroundLake = 23,
            DungeonCrystalCave = 24,
            DungeonCrystalCrossing = 25,
            DungeonCrystalLake = 26,
            DungeonChasmCave = 27,
            DungeonDarkHill = 28,
            DungeonSealedRuin = 29,
            DungeonDeepSealedRuin = 30,
            DungeonSealedRuinPit = 31,
            DungeonDuskForest = 32,
            DungeonDeepDuskForest = 33,
            DungeonTreeshroudForest = 34,
            DungeonBrineCave = 35,
            DungeonLowerBrineCave = 36,
            DungeonBrineCavePit = 37,
            DungeonHiddenLand = 38,
            DungeonHiddenHighland = 39,
            DungeonOldRuins = 40,
            DungeonTemporalTower = 41,
            DungeonTemporalSpire = 42,
            DungeonTemporalPinnacle = 43,
            DungeonMystifyingForest = 44,
            DungeonMystifyingForestClearing = 45,
            DungeonBlizzardIsland = 46,
            DungeonCreviceCave = 47,
            DungeonLowerCreviceCave = 48,
            DungeonCreviceCavePit = 49,
            DungeonSurroundedSea = 50,
            DungeonMiracleSea = 51,
            DungeonDeepMiracleSea = 52,
            DungeonMiracleSeabed = 53,
            DungeonIceAegisCave = 54,
            DungeonRegiceChamber = 55,
            DungeonRockAegisCave = 56,
            DungeonRegirockChamber = 57,
            DungeonSteelAegisCave = 58,
            DungeonRegisteelChamber = 59,
            DungeonAegisCavePit = 60,
            DungeonRegigigasChamber = 61,
            DungeonMtTravail = 62,
            DungeonTheNightmare = 63,
            DungeonSpacialRift = 64,
            DungeonDeepSpacialRift = 65,
            DungeonSpacialRiftBottom = 66,
            DungeonDarkCrater = 67,
            DungeonDeepDarkCrater = 68,
            DungeonDarkCraterPit = 69,
            DungeonConcealedRuins = 70,
            DungeonDeepConcealedRuins = 71,
            DungeonMarineResort = 72,
            DungeonBottomlessSea = 73,
            DungeonBottomlessSeaDepths = 74,
            DungeonShimmerDesert = 75,
            DungeonShimmerDesertPit = 76,
            DungeonMtAvalanche = 77,
            DungeonMtAvalanchePeak = 78,
            DungeonGiantVolcano = 79,
            DungeonGiantVolcanoPeak = 80,
            DungeonWorldAbyss = 81,
            DungeonWorldAbyssPit = 82,
            DungeonSkyStairway = 83,
            DungeonSkyStairwayApex = 84,
            DungeonMysteryJungle = 85,
            DungeonDeepMysteryJungle = 86,
            DungeonSerenityRiver = 87,
            DungeonLandslideCave = 88,
            DungeonLushPrairie = 89,
            DungeonTinyMeadow = 90,
            DungeonLabyrinthCave = 91,
            DungeonOranForest = 92,
            DungeonLakeAfar = 93,
            DungeonHappyOutlook = 94,
            DungeonMyMistral = 95,
            DungeonShimmerHill = 96,
            DungeonLostWilderness = 97,
            DungeonMidnightForest = 98,
            DungeonZeroIsleNorth = 99,
            DungeonZeroIsleEast = 100,
            DungeonZeroIsleWest = 101,
            DungeonZeroIsleSouth = 102,
            DungeonZeroIsleCenter = 103,
            DungeonDestinyTower = 104,
            DungeonDummy0x69 = 105,
            DungeonDummy0x6a = 106,
            DungeonOblivionForest = 107,
            DungeonTreacherousWaters = 108,
            DungeonSoutheasternIslands = 109,
            DungeonInfernoCave = 110,
            Dungeon1stStationPass = 111,
            Dungeon2ndStationPass = 112,
            Dungeon3rdStationPass = 113,
            Dungeon4thStationPass = 114,
            Dungeon5thStationPass = 115,
            Dungeon6thStationPass = 116,
            Dungeon7thStationPass = 117,
            Dungeon8thStationPass = 118,
            Dungeon9thStationPass = 119,
            DungeonSkyPeakSummitPass = 120,
            Dungeon5thStationClearing = 121,
            DungeonSkyPeakSummit = 122,
            DungeonStarCaveSe1 = 123,
            DungeonDeepStarCave = 124,
            DungeonDeepStarCaveTeamRogue = 125,
            DungeonStarCaveDepths = 126,
            DungeonStarCavePit = 127,
            DungeonMurkyForest = 128,
            DungeonEasternCave = 129,
            DungeonFortuneRavine = 130,
            DungeonFortuneRavineDepths = 131,
            DungeonFortuneRavinePit = 132,
            DungeonBarrenValley = 133,
            DungeonDeepBarrenValley = 134,
            DungeonBarrenValleyClearing = 135,
            DungeonDarkWasteland = 136,
            DungeonTemporalTowerSe5 = 137,
            DungeonTemporalSpireSe5 = 138,
            DungeonDuskForestSe5 = 139,
            DungeonBlackSwamp = 140,
            DungeonSpacialCliffs = 141,
            DungeonDarkIceMountain = 142,
            DungeonDarkIceMountainPeak = 143,
            DungeonDarkIceMountainPinnacle = 144,
            DungeonIcicleForest = 145,
            DungeonVastIceMountain = 146,
            DungeonVastIceMountainPeak = 147,
            DungeonVastIceMountainPinnacle = 148,
            DungeonSouthernJungle = 149,
            DungeonBoulderQuarry = 150,
            DungeonDeepBoulderQuarry = 151,
            DungeonBoulderQuarryClearing = 152,
            DungeonRightCavePath = 153,
            DungeonLeftCavePath = 154,
            DungeonLimestoneCavern = 155,
            DungeonDeepLimestoneCavern = 156,
            DungeonLimestoneCavernDepths = 157,
            DungeonSpringCave = 158,
            DungeonUpperSpringCaveHaunter = 159,
            DungeonUpperSpringCave = 160,
            DungeonMiddleSpringCave = 161,
            DungeonLowerSpringCave = 162,
            DungeonSpringCaveDepths = 163,
            DungeonSpringCavePit = 164,
            DungeonLittlePlains = 165,
            DungeonMtClear = 166,
            DungeonChallengeRiver = 167,
            DungeonTrialForest = 168,
            DungeonGuidingSea = 169,
            DungeonHiddenShopkeeperVillage = 170,
            DungeonDummy0xab = 171,
            DungeonDummy0xac = 172,
            DungeonDummy0xad = 173,
            DungeonStarCave = 174,
            DungeonShayminVillage = 175,
            DungeonArmaldosShelter = 176,
            DungeonLuminousSpring = 177,
            DungeonHotSpring = 178,
            DungeonRescue = 179,
            DungeonNormalFlyMaze = 180,
            DungeonDarkFireMaze = 181,
            DungeonRockWaterMaze = 182,
            DungeonGrassMaze = 183,
            DungeonElecSteelMaze = 184,
            DungeonIceGroundMaze = 185,
            DungeonFightPsychMaze = 186,
            DungeonPoisonBugMaze = 187,
            DungeonDragonMaze = 188,
            DungeonGhostMaze = 189,
            DungeonExplorerMaze = 190,
            DungeonFinalMaze = 191,
            DungeonDojo0xc0 = 192,
            DungeonDojo0xc1 = 193,
            DungeonDojo0xc2 = 194,
            DungeonDojo0xc3 = 195,
            DungeonDojo0xc4 = 196,
            DungeonDojo0xc5 = 197,
            DungeonDojo0xc6 = 198,
            DungeonDojo0xc7 = 199,
            DungeonDojo0xc8 = 200,
            DungeonDojo0xc9 = 201,
            DungeonDojo0xca = 202,
            DungeonDojo0xcb = 203,
            DungeonDojo0xcc = 204,
            DungeonDojo0xcd = 205,
            DungeonDojo0xce = 206,
            DungeonDojo0xcf = 207,
            DungeonDojo0xd0 = 208,
            DungeonDojo0xd1 = 209,
            DungeonDojo0xd2 = 210,
            DungeonDojo0xd3 = 211,
            DungeonRescueDungeon = 212,
            DungeonBase = 213,
            DungeonJoinedAtQuestionMarks = 214,
            DungeonBeach = 215,
            DungeonJoinedAtUnknown = 216,
            DungeonJoinedAtBidoof = 217,
            DungeonJoinedAtGrovyle = 218,
            DungeonJoinedAtCelebi = 219,
            DungeonJoinedAtChatot = 220,
            DungeonJoinedAtCresselia = 221,
            DungeonDummy0xde = 222,
            DungeonDummy0xdf = 223,
            DungeonDummy0xe0 = 224,
            DungeonDummy0xe1 = 225,
            DungeonDummy0xe2 = 226,
            DungeonDummy0xe3 = 227,
            DungeonDummy0xe4 = 228,
            DungeonDummy0xe5 = 229,
            DungeonDummy0xe6 = 230,
            DungeonDummy0xe7 = 231,
            DungeonDummy0xe8 = 232,
            DungeonDummy0xe9 = 233,
            DungeonDummy0xea = 234,
            DungeonDummy0xeb = 235,
            DungeonDummy0xec = 236,
            DungeonDummy0xed = 237,
            DungeonDummy0xee = 238,
            DungeonDummy0xef = 239,
            DungeonDummy0xf0 = 240,
            DungeonJoinedAtManaphyRecruited = 241,
            DungeonJoinedAtCresseliaRecruited = 242,
            DungeonJoinedAtShayminLandRecruited = 243,
            DungeonDummy0xf4 = 244,
            DungeonDummy0xf5 = 245,
            DungeonDummy0xf6 = 246,
            DungeonTreasureTown0xf7 = 247,
            DungeonTreasureTown0xf8 = 248,
            DungeonOutside = 249,
            DungeonClient = 250,
            DungeonDummy0xfb = 251,
            DungeonDummy0xfc = 252,
            DungeonDummy0xfd = 253,
            DungeonDummy0xfe = 254,
            DungeonDummy0xff = 255,
        }
        public DungeonId8(KaitaiStream p__io, KaitaiStruct p__parent = null, DungeonId8 p__root = null) : base(p__io)
        {
            m_parent = p__parent;
            m_root = p__root ?? this;
            _read();
        }
        private void _read()
        {
            _dungeonId8Value = ((DungeonId8Enum) m_io.ReadBitsIntLe(8));
        }
        private DungeonId8Enum _dungeonId8Value;
        private DungeonId8 m_root;
        private KaitaiStruct m_parent;
        public DungeonId8Enum DungeonId8Value { get { return _dungeonId8Value; } }
        public DungeonId8 M_Root { get { return m_root; } }
        public KaitaiStruct M_Parent { get { return m_parent; } }
    }
}
