// This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

using Kaitai;

namespace Gale.EOS.Kaitai.NA
{

    /// <summary>
    /// Holds bitsized data for the parent enum fixed_room_id.
    /// </summary>
    public partial class FixedRoomId8 : KaitaiStruct
    {
        public static FixedRoomId8 FromFile(string fileName)
        {
            return new FixedRoomId8(new KaitaiStream(fileName));
        }


        public enum FixedRoomId8Enum
        {
            FixedNone = 0,
            FixedBeachCavePit = 1,
            FixedMtBristlePeak = 2,
            FixedSteamCavePeak = 3,
            FixedAmpClearing = 4,
            FixedUndergroundLake = 5,
            FixedCrystalLake = 6,
            FixedSealedRuinPit = 7,
            FixedBrineCavePit = 8,
            FixedOldRuins = 9,
            FixedTemporalPinnacle = 10,
            FixedMystifyingForestClearing = 11,
            FixedCreviceCavePit = 12,
            FixedMiracleSeabed = 13,
            FixedRegiceChamber = 14,
            FixedRegirockChamber = 15,
            FixedRegisteelChamber = 16,
            FixedRegigigasChamber = 17,
            FixedSpacialRiftBottom = 18,
            FixedDarkCraterPit = 19,
            FixedGiantVolcanoPeak = 20,
            FixedShimmerDesertPit = 21,
            FixedMtAvalanchePeak = 22,
            FixedBottomlessSeaDepths = 23,
            FixedWorldAbyssPit = 24,
            FixedDeepMysteryJungle = 25,
            FixedSkyStairwayApex = 26,
            FixedEmptyOctagon = 27,
            FixedSkyPeak5thStationClearing = 28,
            FixedSkyPeakSummit = 29,
            FixedDeepStarCaveSe1 = 30,
            FixedStarCavePitSe1 = 31,
            FixedFortuneRavinePit = 32,
            FixedBarrenValleyClearing = 33,
            FixedBlackSwamp = 34,
            FixedDarkIceMountainPinnacle = 35,
            FixedVastIceMountainPinnacle = 36,
            FixedBoulderQuarryClearing = 37,
            FixedLimestoneCavernDepths = 38,
            FixedUpperSpringCave = 39,
            FixedMiddleSpringCave = 40,
            FixedSpringCavePit = 41,
            FixedDeepStarCave = 42,
            FixedBarrenValleyClearingRevisit = 43,
            FixedUnused0x2c = 44,
            FixedUnused0x2d = 45,
            FixedUnused0x2e = 46,
            FixedUnused0x2f = 47,
            FixedUnused0x30 = 48,
            FixedUnused0x31 = 49,
            FixedUnused0x32 = 50,
            FixedUnused0x33 = 51,
            FixedUnused0x34 = 52,
            FixedUnused0x35 = 53,
            FixedUnused0x36 = 54,
            FixedUnused0x37 = 55,
            FixedUnused0x38 = 56,
            FixedUnused0x39 = 57,
            FixedUnused0x3a = 58,
            FixedUnused0x3b = 59,
            FixedUnused0x3c = 60,
            FixedUnused0x3d = 61,
            FixedUnused0x3e = 62,
            FixedTest = 63,
            FixedEmptyRectangle = 64,
            FixedBeachCavePitRevisit = 65,
            FixedMtBristlePeakRevisit = 66,
            FixedSteamCavePeakRevisit = 67,
            FixedAmpClearingRevisit = 68,
            FixedUndergroundLakeRevisit = 69,
            FixedCrystalLakeRevisit = 70,
            FixedSealedRuinPitRevisit = 71,
            FixedBrineCavePitRevisit = 72,
            FixedOldRuinsRevisit = 73,
            FixedTemporalPinnacleRevisit = 74,
            FixedRegigigasChamberRevisit = 75,
            FixedSpacialRiftBottomRevisit = 76,
            FixedDarkCraterPitRevisit = 77,
            FixedUnused0x4e = 78,
            FixedUnused0x4f = 79,
            FixedLabyrinthCave = 80,
            FixedZeroIsleNorth = 81,
            FixedZeroIsleEast = 82,
            FixedZeroIsleWest = 83,
            FixedZeroIsleSouth = 84,
            FixedOranForest = 85,
            FixedMarineResort = 86,
            FixedSerenityRiver = 87,
            FixedLandslideCave = 88,
            FixedLushPrairie = 89,
            FixedTinyMeadow = 90,
            FixedSurroundedSea = 91,
            FixedConcealedRuins = 92,
            FixedLakeAfar = 93,
            FixedHappyOutlook = 94,
            FixedMtMistral = 95,
            FixedShimmerHill = 96,
            FixedLostWilderness = 97,
            FixedMidnightForest = 98,
            FixedZeroIsleCenter = 99,
            FixedOblivionForest = 100,
            FixedTreacherousWaters = 101,
            FixedSoutheasternIslands = 102,
            FixedInfernoCave = 103,
            FixedMidnightForestCopy = 104,
            FixedUnused0x69 = 105,
            FixedUnused0x6a = 106,
            FixedUnused0x6b = 107,
            FixedUnused0x6c = 108,
            FixedUnused0x6d = 109,
            FixedSubstituteRoom = 110,
            FixedGoldenChamber = 111,
            FixedSecretBazaar = 112,
            FixedSecretRoom = 113,
            FixedTreasureMemo0 = 114,
            FixedTreasureMemo1 = 115,
            FixedTreasureMemo2 = 116,
            FixedTreasureMemo3 = 117,
            FixedTreasureMemo4 = 118,
            FixedTreasureMemo5 = 119,
            FixedTreasureMemo6 = 120,
            FixedTreasureMemo7 = 121,
            FixedTreasureMemo8 = 122,
            FixedTreasureMemo9 = 123,
            FixedTreasureMemo10 = 124,
            FixedTreasureMemo11 = 125,
            FixedTreasureMemo12 = 126,
            FixedTreasureMemo13 = 127,
            FixedTreasureMemo14 = 128,
            FixedTreasureMemo15 = 129,
            FixedTreasureMemo16 = 130,
            FixedTreasureMemo17 = 131,
            FixedTreasureMemo18 = 132,
            FixedTreasureMemo19 = 133,
            FixedTreasureMemo20 = 134,
            FixedTreasureMemo21 = 135,
            FixedTreasureMemo22 = 136,
            FixedTreasureMemo23 = 137,
            FixedTreasureMemo24 = 138,
            FixedTreasureMemo25 = 139,
            FixedTreasureMemo26 = 140,
            FixedTreasureMemo27 = 141,
            FixedTreasureMemo28 = 142,
            FixedTreasureMemo29 = 143,
            FixedTreasureMemo30 = 144,
            FixedMewtwoChallengeFloor = 145,
            FixedEnteiChallengeFloor = 146,
            FixedRaikouChallengeFloor = 147,
            FixedSuicuneChallengeFloor = 148,
            FixedStarCavePit = 149,
            FixedChallengeLetterFloor1 = 150,
            FixedChallengeLetterFloor2 = 151,
            FixedChallengeLetterFloor3 = 152,
            FixedChallengeLetterFloor4 = 153,
            FixedChallengeLetterFloor5 = 154,
            FixedUnused0x9b = 155,
            FixedUnused0x9c = 156,
            FixedUnused0x9d = 157,
            FixedUnused0x9e = 158,
            FixedUnused0x9f = 159,
            FixedOutlawTeamFloor1 = 160,
            FixedOutlawTeamFloor2 = 161,
            FixedOutlawTeamFloor3 = 162,
            FixedOutlawTeamFloor4 = 163,
            FixedOutlawTeamFloor5 = 164,
            FixedSealedChamber = 165,
            FixedUnused0xa6 = 166,
            FixedUnused0xa7 = 167,
            FixedUnused0xa8 = 168,
            FixedUnused0xa9 = 169,
            FixedClearSilkChamber = 170,
            FixedOrangeSilkChamber = 171,
            FixedGreenSilkChamber = 172,
            FixedIronSilkChamber = 173,
            FixedJoySeedChamber6x = 174,
            FixedFriendBowChamber = 175,
            FixedPinkSilkChamber = 176,
            FixedGraySilkChamber = 177,
            FixedPurpleSilkChamber = 178,
            FixedJoySeedChamber1x = 179,
            FixedRoyalSilkChamber = 180,
            FixedMiracleChestChamber = 181,
            FixedBrownSilkChamber = 182,
            FixedSkySilkChamber = 183,
            FixedGoldSilkChamber = 184,
            FixedBlackSilkChamber = 185,
            FixedJoySeedChamber2x = 186,
            FixedWonderGummiChamber = 187,
            FixedItemChamber1 = 188,
            FixedItemChamber2 = 189,
            FixedWonderChestChamber = 190,
            FixedRedSilkChamber = 191,
            FixedBlueSilkChamber = 192,
            FixedGrassSilkChamber = 193,
            FixedYellowSilkChamber = 194,
            FixedReviverSeedChamber1 = 195,
            FixedReviverSeedChamber2 = 196,
            FixedEmptySealedChamber = 197,
            FixedUnused0xc6 = 198,
            FixedUnused0xc7 = 199,
            FixedUnused0xc8 = 200,
            FixedUnused0xc9 = 201,
            FixedUnused0xca = 202,
            FixedUnused0xcb = 203,
            FixedUnused0xcc = 204,
            FixedUnused0xcd = 205,
            FixedUnused0xce = 206,
            FixedUnused0xcf = 207,
            FixedUnused0xd0 = 208,
            FixedUnused0xd1 = 209,
            FixedUnused0xd2 = 210,
            FixedUnused0xd3 = 211,
            FixedUnused0xd4 = 212,
            FixedUnused0xd5 = 213,
            FixedUnused0xd6 = 214,
            FixedUnused0xd7 = 215,
            FixedUnused0xd8 = 216,
            FixedUnused0xd9 = 217,
            FixedUnused0xda = 218,
            FixedUnused0xdb = 219,
            FixedLegendaryExclusiveChamber1 = 220,
            FixedLegendaryExclusiveChamber2 = 221,
            FixedLegendaryExclusiveChamber3 = 222,
            FixedLegendaryExclusiveChamber4 = 223,
            FixedLegendaryExclusiveChamber5 = 224,
            FixedLegendaryExclusiveChamber6 = 225,
            FixedLegendaryExclusiveChamber7 = 226,
            FixedLegendaryExclusiveChamber8 = 227,
            FixedLegendaryExclusiveChamber9 = 228,
            FixedLegendaryExclusiveChamber10 = 229,
            FixedUnused0xe6 = 230,
            FixedUnused0xe7 = 231,
            FixedUnused0xe8 = 232,
            FixedUnused0xe9 = 233,
            FixedUnused0xea = 234,
            FixedUnused0xeb = 235,
            FixedUnused0xec = 236,
            FixedUnused0xed = 237,
            FixedUnused0xee = 238,
            FixedUnused0xef = 239,
            FixedUnused0xf0 = 240,
            FixedUnused0xf1 = 241,
            FixedUnused0xf2 = 242,
            FixedUnused0xf3 = 243,
            FixedUnused0xf4 = 244,
            FixedUnused0xf5 = 245,
            FixedUnused0xf6 = 246,
            FixedUnused0xf7 = 247,
            FixedUnused0xf8 = 248,
            FixedUnused0xf9 = 249,
            FixedUnused0xfa = 250,
            FixedUnused0xfb = 251,
            FixedUnused0xfc = 252,
            FixedUnused0xfd = 253,
            FixedUnused0xfe = 254,
            FixedUnused0xff = 255,
        }
        public FixedRoomId8(KaitaiStream p__io, KaitaiStruct p__parent = null, FixedRoomId8 p__root = null) : base(p__io)
        {
            m_parent = p__parent;
            m_root = p__root ?? this;
            _read();
        }
        private void _read()
        {
            _fixedRoomId8Value = ((FixedRoomId8Enum) m_io.ReadBitsIntLe(8));
        }
        private FixedRoomId8Enum _fixedRoomId8Value;
        private FixedRoomId8 m_root;
        private KaitaiStruct m_parent;
        public FixedRoomId8Enum FixedRoomId8Value { get { return _fixedRoomId8Value; } }
        public FixedRoomId8 M_Root { get { return m_root; } }
        public KaitaiStruct M_Parent { get { return m_parent; } }
    }
}
