doc: Holds bitsized data for the parent enum exclusive_item_effect_id.
meta:
  id: exclusive_item_effect_id_8
  endian: le
  bit-endian: le
seq:
- id: exclusive_item_effect_id_8_value
  type: b8
  enum: exclusive_item_effect_id_8_enum
enums:
  exclusive_item_effect_id_8_enum:
    0: exclusive_eff_stat_boost
    1: exclusive_eff_no_paralysis
    2: exclusive_eff_no_confusion
    3: exclusive_eff_no_infatuation
    4: exclusive_eff_no_freeze
    5: exclusive_eff_no_critical_hits
    6: exclusive_eff_halved_explosion_damage
    7: exclusive_eff_no_explosion_damage
    8: exclusive_eff_no_move_disabling
    9: exclusive_eff_no_weather_damage
    10: exclusive_eff_no_sleep
    11: exclusive_eff_may_poison_paralyze_sleep_attackers
    12: exclusive_eff_unused_0xc
    13: exclusive_eff_may_sleep_attackers
    14: exclusive_eff_may_nightmare_attackers
    15: exclusive_eff_may_burn_attackers
    16: exclusive_eff_may_paralyze_attackers
    17: exclusive_eff_may_confuse_attackers
    18: exclusive_eff_may_infatuate_attackers
    19: exclusive_eff_may_freeze_attackers
    20: exclusive_eff_may_shadow_hold_attackers
    21: exclusive_eff_may_constrict_attackers
    22: exclusive_eff_may_cringe_attackers
    23: exclusive_eff_may_blinker_attackers
    24: exclusive_eff_may_seal_attacker_moves
    25: exclusive_eff_may_go_invisible_when_attacked
    26: exclusive_eff_may_boost_movement_speed_when_attacked
    27: exclusive_eff_may_warp_when_attacked
    28: exclusive_eff_may_perish_song_attackers
    29: exclusive_eff_may_slow_attackers
    30: exclusive_eff_halved_physical_damage
    31: exclusive_eff_halved_special_damage
    32: exclusive_eff_counter_physical_damage
    33: exclusive_eff_may_bounce_status_moves
    34: exclusive_eff_may_endure
    35: exclusive_eff_counter_25_pct_physical_damage
    36: exclusive_eff_long_toss
    37: exclusive_eff_may_bounce_moves
    38: exclusive_eff_no_stat_drops
    39: exclusive_eff_conversion_2_when_hit
    40: exclusive_eff_no_status_when_clear
    41: exclusive_eff_no_status_when_sunny
    42: exclusive_eff_no_status_when_sandstorm
    43: exclusive_eff_no_status_when_cloudy
    44: exclusive_eff_no_status_when_rainy
    45: exclusive_eff_no_status_when_hail
    46: exclusive_eff_no_status_when_foggy
    47: exclusive_eff_movement_speed_boost_when_clear
    48: exclusive_eff_movement_speed_boost_when_sunny
    49: exclusive_eff_movement_speed_boost_when_sandstorm
    50: exclusive_eff_movement_speed_boost_when_cloudy
    51: exclusive_eff_movement_speed_boost_when_rainy
    52: exclusive_eff_movement_speed_boost_when_hail
    53: exclusive_eff_movement_speed_boost_when_foggy
    54: exclusive_eff_attack_speed_boost_when_clear
    55: exclusive_eff_attack_speed_boost_when_sunny
    56: exclusive_eff_attack_speed_boost_when_sandstorm
    57: exclusive_eff_attack_speed_boost_when_cloudy
    58: exclusive_eff_attack_speed_boost_when_rainy
    59: exclusive_eff_attack_speed_boost_when_hail
    60: exclusive_eff_attack_speed_boost_when_foggy
    61: exclusive_eff_evasion_boost_when_clear
    62: exclusive_eff_evasion_boost_when_sunny
    63: exclusive_eff_evasion_boost_when_sandstorm
    64: exclusive_eff_evasion_boost_when_cloudy
    65: exclusive_eff_evasion_boost_when_rainy
    66: exclusive_eff_evasion_boost_when_hail
    67: exclusive_eff_evasion_boost_when_foggy
    68: exclusive_eff_bypass_reflect_light_screen
    69: exclusive_eff_scrappy
    70: exclusive_eff_miracle_eye
    71: exclusive_eff_restore_pp_on_new_floors
    72: exclusive_eff_restore_hp_on_new_floors
    73: exclusive_eff_increased_hp_recovery
    74: exclusive_eff_max_pp_boost
    75: exclusive_eff_unused_0x4b
    76: exclusive_eff_max_hp_boost_10
    77: exclusive_eff_max_hp_boost_20
    78: exclusive_eff_max_hp_boost_30
    79: exclusive_eff_exp_boost
    80: exclusive_eff_exp_from_damage
    81: exclusive_eff_may_restore_pp_from_damage
    82: exclusive_eff_may_not_consume_pp
    83: exclusive_eff_thrown_item_protection
    84: exclusive_eff_bounce_thrown_items
    85: exclusive_eff_extend_self_effects_to_team
    86: exclusive_eff_more_treasure_drops
    87: exclusive_eff_hp_drain_recovery_boost
    88: exclusive_eff_pressure_boost
    89: exclusive_eff_no_status
    90: exclusive_eff_halved_damage
    91: exclusive_eff_damage_boost_50_pct
    92: exclusive_eff_absorb_teammate_poison
    93: exclusive_eff_recover_hp_from_apples_and_berries
    94: exclusive_eff_more_kecleon_shops
    95: exclusive_eff_more_hidden_stairs
    96: exclusive_eff_no_friendly_fire
    97: exclusive_eff_pickup_boost
    98: exclusive_eff_more_money_drops
    99: exclusive_eff_unused_0x63
    100: exclusive_eff_recover_hp_from_watery_terrain
    101: exclusive_eff_heal_status_from_watery_terrain
    102: exclusive_eff_no_fire_damage
    103: exclusive_eff_no_water_damage
    104: exclusive_eff_no_grass_damage
    105: exclusive_eff_no_electric_damage
    106: exclusive_eff_no_fighting_damage
    107: exclusive_eff_no_ground_damage
    108: exclusive_eff_no_flying_damage
    109: exclusive_eff_no_psychic_damage
    110: exclusive_eff_no_ghost_damage
    111: exclusive_eff_no_dragon_damage
    112: exclusive_eff_no_dark_damage
    113: exclusive_eff_no_steel_damage
    114: exclusive_eff_absorb_fire_damage
    115: exclusive_eff_absorb_water_damage
    116: exclusive_eff_absorb_grass_damage
    117: exclusive_eff_absorb_electric_damage
    118: exclusive_eff_absorb_ice_damage
    119: exclusive_eff_absorb_fighting_damage
    120: exclusive_eff_absorb_ground_damage
    121: exclusive_eff_absorb_flying_damage
    122: exclusive_eff_absorb_psychic_damage
    123: exclusive_eff_absorb_bug_damage
    124: exclusive_eff_absorb_rock_damage
    125: exclusive_eff_absorb_ghost_damage
    126: exclusive_eff_absorb_dragon_damage
    127: exclusive_eff_absorb_dark_damage
    128: exclusive_eff_absorb_steel_damage
    129: exclusive_eff_last
